# this is a configuration file for PostgresSQL database
# it contains the database name, user, password, host, port
host: "localhost"
port: 5432
user: "postgres"
password: "postgres"
dbname: "postgres"
sslmode: "disable"
